stable_version: 2.7.12
stable_version_minor: 2.7
stable_release_url: https://github.com/IronLanguages/ironpython2/releases/tag/ipy-2.7.12
stable_release_date: 2.7.12 released on 2022-01-21
stable_release_notes: https://github.com/IronLanguages/ironpython2/releases/tag/ipy-2.7.12
stable_release_source: https://github.com/IronLanguages/ironpython2/archive/ipy-2.7.12.zip

preview_version: 3.4.0-beta1
preview_version_minor: 3.4
preview_release_url: https://github.com/IronLanguages/ironpython3/releases/tag/v3.4.0-beta1
preview_release_date: 3.4.0-beta1 released on 2022-04-30
preview_release_notes: https://github.com/IronLanguages/ironpython3/releases/tag/v3.4.0-beta1
preview_release_source: https://github.com/IronLanguages/ironpython3/archive/v3.4.0-beta1.zip

paginate: 10
paginate_path: "/blog/page:num/"
